sudo: required
language: node_js 
services:
    - docker

before_install:
    - docker build -t vidalgp/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true vidalgp/docker-react npm run test
